name: CI

on:
  push:
    paths:
      - "**/*.py"
      - pyproject.toml
      - uv.lock
      - ".github/workflows/ci.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "**/*.py"
      - pyproject.toml
      - uv.lock
      - ".github/workflows/ci.yaml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-python: true

      - name: Setup project
        run: uv sync --locked --all-extras --dev

      - parallel:
          - name: Run linting
            run: uv run ruff check src
          - name: Run type checking
            run: uv run mypy src
